### ISSUE TITLE
Upload wheels for linux platform

### ISSUE THREAD

**Issue by Gr1N** [noirello/bonsai#11]
Please, if it possible, upload wheels for linux platform, we can always build from sources, but wheel more useful.

**Comment by noirello** [comment]
It's not possible (yet) to use wheel distribution on Linux.

As far as I know, the current implementation of wheel is not able to store information about Linux distributions which is a problem, because for example a Debian-based distro uses different libraries then a Red Hat-based one. So a module compiled and wheel packaged on one of them won't work on the other distribution.

But the developers of wheel are already working on [this](https://www.python.org/dev/peps/pep-0513/). So stay tuned :)
